spring:
  application:
    name: ElectionApplication
  profiles:
    active:
      - "postgresql"
voters:
  adulthood:
    threshold-age: 18
constraints:
  pesel-unique: uk_voters_pesel

vote:
  constraints:
    vote-per-election-unique: votes_unique_voter_per_election

server:
  port: 8082
